# Generated by Django 3.1.2 on 2020-10-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('register_dttm', models.DateField(auto_now_add=True)),
                ('areaid', models.TextField(max_length=10)),
            ],
        ),
    ]
