# Generated by Django 3.1.2 on 2020-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201020_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='bikeuser',
            name='username',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='사용자명'),
        ),
    ]
