# Generated by Django 3.1.2 on 2020-10-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('rackTotCnt', models.IntegerField()),
                ('stationName', models.CharField(max_length=100)),
                ('parkingBikeTotCnt', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('stationLatitude', models.FloatField()),
                ('stationLongitude', models.FloatField()),
                ('stationId', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
