# Generated by Django 3.1.2 on 2020-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayTot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('tot_getoff', models.FloatField()),
                ('tot_ride', models.FloatField()),
            ],
            options={
                'db_table': 'subway_tot',
            },
        ),
    ]
