# Generated by Django 3.1.2 on 2020-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stationId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
