# Generated by Django 3.1.2 on 2020-11-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_auto_20201119_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='S06',
        ),
    ]
