# Generated by Django 3.1.2 on 2020-11-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0004_remove_weather_s06'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='S06',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
