# Generated by Django 3.1 on 2020-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestampedmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timestampedmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
