# Generated by Django 3.1.2 on 2020-11-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0002_subwaytot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='dsnw',
            new_name='PTY',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='hm',
            new_name='REH',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='hr3Fhsc',
            new_name='RN1',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='icsr',
            new_name='S06',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='rn',
            new_name='T1H',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ss',
            new_name='VEC',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ta',
            new_name='WSD',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wd',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='ws',
        ),
        migrations.AddField(
            model_name='weather',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
