# Generated by Django 3.1.3 on 2020-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0005_weather_s06'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayRideGetoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('SubGetoff', models.IntegerField()),
                ('SubRide', models.IntegerField()),
            ],
            options={
                'db_table': 'subway_RideGetoff',
            },
        ),
    ]
