# Generated by Django 3.1.3 on 2020-11-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0006_subwayridegetoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('rentVal', models.IntegerField(default=0)),
                ('returnVal', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'predicted_value',
            },
        ),
    ]
