# Generated by Django 3.1.3 on 2020-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0007_predictvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='SKY',
            field=models.FloatField(default=0),
        ),
    ]
