# Generated by Django 3.1 on 2020-12-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201201_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationNow',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('parkingBikeTotCnt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'station_now',
            },
            bases=('core.timestampedmodel',),
        ),
    ]
