# Generated by Django 3.1 on 2020-12-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationNow',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('parkingBikeTotCnt', models.IntegerField(default=0)),
                ('station', models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, related_name='stationNow', to='station.stations')),
            ],
            options={
                'db_table': 'station_now',
            },
            bases=('core.timestampedmodel',),
        ),
    ]
