# Generated by Django 3.1 on 2020-12-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        ('bikemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationnow',
            name='station',
            field=models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, to='station.stations'),
        ),
    ]
