# Generated by Django 3.1 on 2020-12-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_stations_areaid'),
        ('bikemap', '0002_stationnow_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationnow',
            name='station',
            field=models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='station.stations'),
        ),
    ]
