# Generated by Django 3.1 on 2020-12-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='areaId',
            field=models.ForeignKey(db_column='areaId', on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='user.users'),
        ),
    ]
